reviewdog: Use mypy baseline for reviewdog PR runs

diff --git a/.github/workflows/reviewdog.yml b/.github/workflows/reviewdog.yml
--- a/.github/workflows/reviewdog.yml
+++ b/.github/workflows/reviewdog.yml
@@ -100,4 +100,16 @@ jobs:
           REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
           . .venv/bin/activate
-          reviewdog -reporter=github-pr-check -log-level=debug
+          REVIEWDOG_ARGS="-reporter=github-pr-check -fail-level=error"
+          echo running reviewdog
+          reviewdog -runners=ruff -filter-mode=added $REVIEWDOG_ARGS
+          echo running mypy
+          mypy . > ${{ runner.temp }}/mypy-output.txt || mypy_exit=$?
+          if [[ $mypy_exit -ne 0 && $mypy_exit -ne 1 ]]; then
+            echo "mypy failed with exit code $mypy_exit"
+            cat ${{ runner.temp }}/mypy-output.txt
+            exit $mypy_exit
+          fi
+          cat ${{ runner.temp }}/mypy-output.txt | mypy-baseline filter --hide-stats > ${{ runner.temp }}/mypy-baselined-output.txt || baseline_exit=$?
+          echo running reviewdog again for mypy
+          reviewdog -f=mypy -name=mypy -filter-mode=nofilter $REVIEWDOG_ARGS < ${{ runner.temp }}/mypy-baselined-output.txt
